version: '3.9'

services:
  web:
    image: ${DOCKER_REGISTRY-}dockertarea
    build:
      context: .
      dockerfile: DockerTarea/Dockerfile
    ports:
      - "8000:80"
    
    networks:
      - dockertarea_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - dockertarea_network

networks:
  dockertarea_network: